version: '3.8'

services:
  restaurant-recommendation-redis:
    image: redis:latest
    container_name: restaurant-recommendation-redis
    ports:
      - "6379:6379"
    environment:
      TZ: "${TZ}"

  restaurant-recommendation-database:
    image: mysql:latest
    container_name: restaurant-recommendation-database
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"

  restaurant-recommendation-app:
    container_name: restaurant-recommendation-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - restaurant-recommendation-redis
      - restaurant-recommendation-database
    image: 22cun2/restaurant-recommendation-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATABASE_URL=${SPRING_DATABASE_URL}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always