server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY}
    key-store-type: PKCS12
    key-alias: myalias
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  thymeleaf3:
    decoupled-logic: true
  data:
    redis:
      host: localhost
      port: 6379
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 1800
sse:
  timeout: 1800

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: ${SPRING_DATABASE_URL}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}